services:
  db:
    image: mongo:6.0
    container_name: mongodb
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb://db:27017/videojuegos?authSource=admin"
      JWT_SECRET: "your_super_secret_jwt_key_123"
      PORT: 3000
      OLLAMA_URL: "http://ollama:11434"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
      - ollama

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  mongo_data:
  ollama_data:
